#!/usr/bin/env python3
"""RemnaWatch Interactive Installation Wizard"""

import os
import sys
from pathlib import Path


def prompt(question: str, default: str = "", sensitive: bool = False) -> str:
    if default:
        question = f"{question} [{default}]: "
    else:
        question = f"{question}: "

    if sensitive:
        import getpass
        value = getpass.getpass(question)
    else:
        value = input(question).strip()

    if not value and default:
        return default
    return value


def main():
    print("=" * 60)
    print("  RemnaWatch — Interactive Installation Wizard")
    print("=" * 60)
    print()

    print("This wizard will create a .env file with your configuration.")
    print()

    config = {}

    config["BOT_TOKEN"] = prompt(
        "Telegram Bot Token",
        sensitive=True,
    )
    while not config["BOT_TOKEN"]:
        print("  ERROR: Bot token is required!")
        config["BOT_TOKEN"] = prompt("Telegram Bot Token", sensitive=True)

    admin_ids = prompt("Admin Telegram IDs (comma-separated, e.g. 12345,67890)")
    while not admin_ids:
        print("  ERROR: At least one admin ID is required!")
        admin_ids = prompt("Admin Telegram IDs (comma-separated)")
    config["ADMIN_IDS"] = admin_ids

    config["REMNA_API_URL"] = prompt(
        "Remnawave API URL (e.g. https://panel.example.com)"
    )
    while not config["REMNA_API_URL"]:
        print("  ERROR: API URL is required!")
        config["REMNA_API_URL"] = prompt("Remnawave API URL")

    config["REMNA_API_TOKEN"] = prompt(
        "Remnawave JWT Token",
        sensitive=True,
    )
    while not config["REMNA_API_TOKEN"]:
        print("  ERROR: JWT Token is required!")
        config["REMNA_API_TOKEN"] = prompt("Remnawave JWT Token", sensitive=True)

    config["MONITOR_USER_UUID"] = prompt("Monitoring User UUID (ACTIVE user from /api/users)")
    while not config["MONITOR_USER_UUID"]:
        print("  ERROR: User UUID is required!")
        config["MONITOR_USER_UUID"] = prompt("Monitoring User UUID")

    config["SINGBOX_BIN"] = prompt(
        "sing-box binary path",
        default="/usr/local/bin/sing-box",
    )

    config["DB_PATH"] = prompt(
        "Database path",
        default="./data/bot.db",
    )

    config["LOG_PATH"] = prompt(
        "Log file path",
        default="./logs/bot.log",
    )

    config["TZ"] = prompt("Timezone", default="Europe/Moscow")

    print()
    print("-" * 60)
    print("  Configuration summary:")
    print("-" * 60)
    for key, value in config.items():
        if key in ("BOT_TOKEN", "REMNA_API_TOKEN"):
            shown = value[:8] + "..." if len(value) > 8 else "***"
        else:
            shown = value
        print(f"  {key}: {shown}")

    print()
    confirm = input("Write to .env? [Y/n]: ").strip().lower()
    if confirm and confirm not in ("y", "yes", ""):
        print("Aborted.")
        return

    env_path = Path(".env")
    with open(env_path, "w", encoding="utf-8") as f:
        f.write("# RemnaWatch Configuration\n")
        f.write("# Generated by install.py\n\n")
        for key, value in config.items():
            f.write(f"{key}={value}\n")

    print(f"\n✅ Configuration written to {env_path.absolute()}")
    print()
    print("To start RemnaWatch:")
    print("  pip install -r requirements.txt")
    print("  python -m src.main")
    print()
    print("Or with Docker:")
    print("  docker compose up -d")


if __name__ == "__main__":
    main()
